// Keep the workers.dev preview out of search while allowing the custom domain to index.
// @ts-ignore Generated by the Cloudflare build, not present in a normal Next build.
import worker from "./.open-next/worker.js";

type WorkerEnv = {
  ASSETS: { fetch(request: Request): Promise<Response> };
  WORKER_SELF_REFERENCE: { fetch(request: Request): Promise<Response> };
};

export default {
  async fetch(request: Request, env: WorkerEnv, context: unknown) {
    const url = new URL(request.url);
    if (url.hostname === "fluidrwa.com") {
      url.hostname = "www.fluidrwa.com";
      return Response.redirect(url.toString(), 308);
    }

    const image = url.pathname === "/_next/image" ? url.searchParams.get("url") : null;
    // Serve local originals until Cloudflare image transformation is configured.
    const localImage = image && image.startsWith("/assets/") && !image.includes("..") && !image.includes("\\");
    const response = localImage
      ? await env.ASSETS.fetch(new Request(new URL(image, url.origin), { method: request.method }))
      : await worker.fetch(request, env, context);
    if (!url.hostname.endsWith(".workers.dev")) return response;

    const headers = new Headers(response.headers);
    headers.set("X-Robots-Tag", "noindex, nofollow");
    return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
  },

  async scheduled(
    _controller: unknown,
    env: WorkerEnv,
    context: { waitUntil(promise: Promise<unknown>): void }
  ) {
    context.waitUntil(
      env.WORKER_SELF_REFERENCE.fetch(new Request("https://www.fluidrwa.com/api/market-signals/ingest")).then((response) => {
        if (!response.ok) throw new Error(`Market signal ingestion failed: HTTP ${response.status}`);
      })
    );
  }
};
