// Keep the workers.dev preview out of search while allowing the custom domain to index.
// @ts-ignore Generated by the Cloudflare build, not present in a normal Next build.
import worker from "./.open-next/worker.js";
import { blockedIncidentSource, formRequestRejection } from "./lib/formAbuse";

type WorkerEnv = {
  ASSETS: { fetch(request: Request): Promise<Response> };
  WORKER_SELF_REFERENCE: { fetch(request: Request): Promise<Response> };
  FORM_RATE_LIMITER: { limit(options: { key: string }): Promise<{ success: boolean }> };
};

export default {
  async fetch(request: Request, env: WorkerEnv, context: unknown) {
    const url = new URL(request.url);
    if (blockedIncidentSource(request)) {
      return Response.json({ ok: false, code: "request_rejected", message: "This request could not be accepted." }, { status: 403 });
    }
    const intakePaths = ["/api/vendor-intro-request", "/api/vendor-comparison-lead", "/api/tokenization-assessment", "/api/family-office-stack-assessment", "/api/freelancer-contact-request", "/api/freelancer-marketplace-waitlist", "/api/freelancer-profile"];
    if (request.method === "POST" && intakePaths.includes(url.pathname)) {
      const rejection = formRequestRejection(request);
      if (rejection) return Response.json({ ok: false, code: rejection, message: "Please reload the form and try again, or email contact@fluidrwa.com." }, { status: rejection === "request_too_large" ? 413 : 403 });
      const ip = request.headers.get("cf-connecting-ip");
      if (ip && env.FORM_RATE_LIMITER) {
        try {
          const { success } = await env.FORM_RATE_LIMITER.limit({ key: `fluidrwa-form:${ip}` });
          if (!success) return Response.json({ ok: false, code: "submission_rate_limit", message: "Too many attempts. Please wait one minute and try again. Your details are still in the form." }, { status: 429, headers: { "Retry-After": "60", "Cache-Control": "no-store" } });
        } catch {
          // Preserve lead delivery during limiter outages; payload checks still run in the API.
          console.error("form rate limiter unavailable");
        }
      }
    }
    if (url.hostname === "fluidrwa.com") {
      url.hostname = "www.fluidrwa.com";
      return Response.redirect(url.toString(), 308);
    }

    const image = url.pathname === "/_next/image" ? url.searchParams.get("url") : null;
    // Serve local originals until Cloudflare image transformation is configured.
    const localImage = image && image.startsWith("/assets/") && !image.includes("..") && !image.includes("\\");
    const response = localImage
      ? await env.ASSETS.fetch(new Request(new URL(image, url.origin), { method: request.method }))
      : await worker.fetch(request, env, context);
    if (!url.hostname.endsWith(".workers.dev")) return response;

    const headers = new Headers(response.headers);
    headers.set("X-Robots-Tag", "noindex, nofollow");
    return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
  },

  async scheduled(
    _controller: unknown,
    env: WorkerEnv,
    context: { waitUntil(promise: Promise<unknown>): void }
  ) {
    context.waitUntil(
      env.WORKER_SELF_REFERENCE.fetch(new Request("https://www.fluidrwa.com/api/market-signals/ingest")).then((response) => {
        if (!response.ok) throw new Error(`Market signal ingestion failed: HTTP ${response.status}`);
      })
    );
  }
};
