export type UseCaseGuide = {
  title: string;
  group: "Financial services" | "Enterprise operations" | "Consumer applications";
  audience: string;
  answer: string;
  workflow: { title: string; detail: string }[];
  controls: { risk: string; control: string }[];
  notFit: string;
  measures: string[];
  pilot: string[];
  questions: string[];
  reference: { label: string; href: string; note: string };
  faqs: { q: string; a: string }[];
};

export const useCaseGuides: Record<string, UseCaseGuide> = {
  "healthcare-credentials-consent": {
    title: "Healthcare credentials and consent", group: "Enterprise operations", audience: "Hospital IT leaders, research sponsors and clinical network operators",
    answer: "Verifiable credentials can let an organization check who issued a professional qualification or patient permission. They do not replace clinical records, consent law or access management. The useful design keeps sensitive records in controlled systems and verifies only the evidence needed for a particular request.",
    workflow: [
      { title: "Establish trust", detail: "Identify the clinical body or hospital authorized to issue a credential. Define which receiving organizations accept it and what evidence they need." },
      { title: "Record permission", detail: "Capture the purpose, permitted recipient, expiry and version of the consent in the consent system. Avoid publishing identifying clinical data on a public ledger." },
      { title: "Verify access", detail: "Check the issuer, credential status and requested scope before a clinical application grants access. A valid signature alone is not an authorization decision." },
      { title: "Revoke and audit", detail: "Propagate changed permissions to downstream systems. Retain a controlled audit record of who accessed what, under which consent version." }
    ],
    controls: [
      { risk: "Sensitive metadata exposure", control: "Minimize identifiers and prevent correlation across presentations; keep medical content off public chains." },
      { risk: "Revoked consent remains usable", control: "Check status at access time and define how quickly every connected application must honor a change." },
      { risk: "Untrusted credential issuer", control: "Maintain an issuer allowlist and validate professional authority separately from cryptographic authenticity." }
    ],
    notFit: "A single hospital with a functioning internal identity system may not need a shared credential network. Start with ordinary access-control integration if that solves the actual bottleneck.",
    measures: ["Time to verify an external credential", "Consent revocation propagation time", "Unauthorized access and unresolved audit exceptions"],
    pilot: ["Choose one cross-organization credential and one receiving application.", "Agree on issuer authority, data minimization and permission semantics.", "Test expiration, revocation, a compromised issuer and an unavailable status service.", "Compare verification effort with the existing manual process before expanding."],
    questions: ["Which patient identifiers leave our environment?", "Can revocation be enforced in every connected clinical application?", "What happens when verification is unavailable during urgent care?"],
    reference: { label: "W3C Verifiable Credentials Data Model", href: "https://www.w3.org/TR/vc-data-model-2.0/", note: "A technical foundation for issuer, holder and verifier roles; not a healthcare-specific approval or a substitute for privacy review." },
    faqs: [{ q: "Should patient records be stored onchain?", a: "A public ledger is generally a poor default for sensitive clinical content. Keep records in controlled systems and assess even hashes and metadata for privacy risks." }, { q: "Does a credential prove consent is still valid?", a: "Not by itself. The application must check current status, purpose and permissions when access is requested." }]
  },
  "maritime-trade-documents": {
    title: "Digital trade documents and cargo provenance", group: "Enterprise operations", audience: "Trade banks, carriers, freight forwarders and exporters",
    answer: "A digital trade-document workflow coordinates issuance, control, endorsement and surrender of records such as bills of lading. Its value depends on acceptance across the trade corridor and a reliable link to legal rights, not on adding a blockchain timestamp to a PDF.",
    workflow: [
      { title: "Issue the record", detail: "The carrier creates the authoritative electronic document and identifies the party in control. Connect shipment identifiers without confusing cargo tracking with document title." },
      { title: "Review and finance", detail: "Exporters, importers and banks review required fields and supporting documents. Route discrepancies to a named operations owner before releasing finance." },
      { title: "Transfer control", detail: "Record endorsement and exclusive control changes using a method accepted by the participating parties. Prevent two versions from acting as the same transferable record." },
      { title: "Surrender and settle", detail: "Validate surrender for cargo release, reconcile payment evidence and close the document lifecycle. Include a controlled paper fallback where legally supported." }
    ],
    controls: [{ risk: "Record not accepted in the corridor", control: "Obtain local legal analysis and explicit carrier, bank and counterparty acceptance." }, { risk: "Duplicate document control", control: "Test singularity, endorsement, surrender and change-of-medium procedures." }, { risk: "Incorrect cargo evidence", control: "Authenticate event sources and separate shipping milestones from title and financing decisions." }],
    notFit: "Do not build a new ledger when the major carrier or financing bank will not accept its records. An accepted electronic document platform may be the better route.",
    measures: ["Document discrepancy resolution time", "Time from issuance to financing approval", "Duplicate or failed surrender events"],
    pilot: ["Select one corridor with cooperating carrier and bank.", "Map issuance, endorsement, financing, surrender and fallback responsibilities.", "Test an amended document, disputed control and a failed cargo-release instruction.", "Measure turnaround against comparable paper transactions."],
    questions: ["Who has exclusive control at each stage?", "Which jurisdictions and banks accept the record?", "How are paper conversion and disputed endorsements handled?"],
    reference: { label: "UNCITRAL Model Law on Electronic Transferable Records", href: "https://uncitral.un.org/en/texts/ecommerce/modellaw/electronic_transferable_records", note: "Explains functional equivalence, integrity and control. It is a model law; adoption and substantive rights must be checked for the relevant jurisdictions." },
    faqs: [{ q: "Is a scanned bill of lading an electronic transferable record?", a: "A scan alone does not establish exclusive control or the other characteristics needed for a transferable electronic record." }, { q: "Is blockchain required for electronic bills of lading?", a: "No. MLETR is technology-neutral. Evaluate reliable control, interoperability and legal acceptance before selecting the technology." }]
  },
  "carbon-credit-mrv": {
    title: "Carbon credit verification and retirement", group: "Enterprise operations", audience: "Project developers, registries and corporate carbon buyers",
    answer: "Digital MRV and retirement systems connect project evidence to a credit's issuance, ownership and final retirement. A token can improve record handling, but it cannot establish additionality, correct a weak baseline or make an unverified credit high quality.",
    workflow: [{ title: "Collect project evidence", detail: "Capture measurements, methodology, monitoring period and provenance. Record who supplied each observation and how it was validated." }, { title: "Validate and issue", detail: "Independent verification and the crediting program determine issuance. Link the approved credit serial numbers to the digital record." }, { title: "Reconcile transfers", detail: "Keep digital ownership aligned with the authoritative registry. Any representation outside the registry needs explicit rules against duplicate issuance or use." }, { title: "Retire and report", detail: "Record beneficiary, purpose and retirement evidence. Prevent a retired credit from continuing to circulate as an available offset." }],
    controls: [{ risk: "Double counting", control: "Reconcile issuance, use and retirement against authoritative registry identifiers." }, { risk: "Weak project evidence", control: "Assess methodology, additionality, permanence and independent verification before automating records." }, { risk: "Misleading buyer claims", control: "Separate credit ownership from the right to make an environmental claim and retain the supporting disclosures." }],
    notFit: "Avoid tokenization if the registry does not permit the proposed representation or reliable reconciliation cannot be established. Improve project evidence first.",
    measures: ["Registry reconciliation exceptions", "Time to produce retirement evidence", "Evidence completeness per monitoring period"],
    pilot: ["Choose one methodology and a cooperative crediting program.", "Map serial identifiers, ownership and retirement status across systems.", "Test a reversal, invalid credit, duplicate issuance and delayed registry update.", "Have an independent reviewer inspect the resulting buyer evidence pack."],
    questions: ["Which registry is authoritative?", "How are reversals and permanence risks recorded?", "Can a token remain transferable after registry retirement?"],
    reference: { label: "ICVCM Core Carbon Principles", href: "https://icvcm.org/core-carbon-principles/", note: "A quality framework covering governance, tracking, quantification and double counting. Digital infrastructure should support evidence against these principles, not substitute for it." },
    faqs: [{ q: "Does tokenization improve carbon credit quality?", a: "Not inherently. Quality comes from the mitigation activity, methodology, verification and safeguards. Tokenization changes record handling." }, { q: "What proves a credit was retired?", a: "Use authoritative registry evidence linked to the credit identifiers and beneficiary, with reconciliation to any digital representation." }]
  },
  "gaming-asset-ownership": {
    title: "Digital loyalty, tickets and memberships", group: "Consumer applications", audience: "Consumer brands, venues, sports organizations and membership platforms",
    answer: "Digital membership and ticket systems can connect purchase, access and rewards across participating businesses. Transferable tokens are useful only when portability or controlled resale solves a genuine customer problem. Most users should not need to manage crypto to use a ticket.",
    workflow: [{ title: "Join or purchase", detail: "Use familiar checkout and account recovery. Explain entitlement, refund and transfer terms before payment." }, { title: "Issue entitlement", detail: "Connect the membership or ticket to a usable account. Separate the right to attend an event from unrelated collectible ownership." }, { title: "Redeem benefits", detail: "Venues or partner applications verify eligibility and record redemption without exposing unnecessary customer history." }, { title: "Transfer or recover", detail: "Apply resale and refund rules consistently. Recover lost access without creating two redeemable copies of the same entitlement." }],
    controls: [{ risk: "Account takeover or lost access", control: "Provide secure recovery, device controls and support escalation." }, { risk: "Duplicate entry or reward abuse", control: "Use atomic redemption checks and a documented offline-entry procedure." }, { risk: "Unclear consumer rights", control: "Specify expiry, resale, refunds and benefit changes in accessible terms." }],
    notFit: "If benefits are confined to one brand and never need portability, a conventional loyalty database is likely simpler and cheaper.",
    measures: ["Checkout and activation completion", "Failed entry and duplicate redemption rates", "Recovery support time"],
    pilot: ["Start with one venue or benefit and ordinary payment methods.", "Test purchase, refund, transfer and recovery with non-crypto users.", "Simulate poor connectivity and duplicate entry at peak load.", "Compare retention and support costs with the existing program."],
    questions: ["Can members recover access without a seed phrase?", "How does redemption work when venue connectivity fails?", "Which benefits genuinely work across independent partners?"],
    reference: { label: "W3C Verifiable Credentials Data Model", href: "https://www.w3.org/TR/vc-data-model-2.0/", note: "An alternative technical pattern for proving membership attributes. It does not require every entitlement to become a tradeable asset." },
    faqs: [{ q: "Do customers need a crypto wallet?", a: "Not necessarily. Account-based experiences and embedded wallet services can hide unnecessary technical complexity, provided recovery and custody responsibilities are clear." }, { q: "Should every loyalty program use tokens?", a: "No. Use tokens only when interoperability or transferability adds measurable value beyond a conventional program." }]
  },
  "insurance-claims-parametric-risk": {
    title: "Insurance claims and parametric payouts", group: "Financial services", audience: "Insurers, brokers, claims operations and risk-data teams",
    answer: "Claims automation organizes policy terms, evidence, review and payment. Parametric products instead pay according to a predefined event trigger. These are different workflows: a trigger can accelerate a decision but may not reflect the policyholder's actual loss.",
    workflow: [{ title: "Define coverage", detail: "Specify covered events, exclusions, trigger calculation and dispute rights. For parametric products, evaluate how the chosen index relates to losses." }, { title: "Receive evidence", detail: "Authenticate event feeds or claimant documents. Track missing, late or contradictory inputs rather than treating the first feed as unquestionable." }, { title: "Approve the decision", detail: "Apply approved policy logic and route exceptions to qualified reviewers. Preserve the input and rule version that produced the decision." }, { title: "Pay and reconcile", detail: "Verify the recipient, release approved funds and track receipt. Keep payment automation separate from underwriting and claims authority." }],
    controls: [{ risk: "Basis risk", control: "Test historical events where the index and actual losses diverge; explain limitations to buyers." }, { risk: "Data feed failure", control: "Define backup evidence, stale-data thresholds and manual review." }, { risk: "Unreviewable automated decisions", control: "Retain policy versions, input evidence and a workable appeal process." }],
    notFit: "Avoid fully automated payout decisions where damage requires nuanced assessment, the trigger is poorly correlated with loss, or data cannot be independently checked.",
    measures: ["Time from verified event to approved payment", "Exception and appeal rates", "Trigger-versus-loss divergence"],
    pilot: ["Select one bounded policy and claims scenario.", "Back-test the trigger against actual event and loss data.", "Simulate missing feeds, a disputed event and failed recipient payment.", "Keep human approval until operational and policy owners accept the results."],
    questions: ["Who can amend the trigger or override a decision?", "What independent evidence validates event data?", "How are policyholders protected when the trigger misses their loss?"],
    reference: { label: "EIOPA paper on measures to improve insurability", href: "https://www.eiopa.europa.eu/system/files/2023-09/EIOPA-21-046_eiopa-staff-paper-on-measures-to-improve-insurability.pdf", note: "Discusses insurance protection approaches and the limitations of parametric triggers. It is background research, not product authorization." },
    faqs: [{ q: "Is parametric insurance the same as automated claims?", a: "No. Parametric insurance uses agreed event triggers; conventional claims generally assess covered loss and evidence." }, { q: "Can a smart contract remove basis risk?", a: "No. Automating an index-based rule does not improve the relationship between the index and a policyholder's actual loss." }]
  },
  "supply-chain-provenance": {
    title: "Product passports and supply chain provenance", group: "Enterprise operations", audience: "Manufacturers, procurement teams and product compliance leaders",
    answer: "A product passport connects a product identifier with origin, composition, certifications and lifecycle events. Shared records help organizations exchange evidence, but a reliable scan or ledger entry does not prove the physical item itself is authentic.",
    workflow: [{ title: "Identify the item", detail: "Choose product, batch or serialized-item granularity. Link identifiers to ERP records and a physical label that suits the product's lifecycle." }, { title: "Collect supplier evidence", detail: "Request structured origin and material data with supplier credentials. Record provenance, expiry and verification of certificates." }, { title: "Record custody events", detail: "Authenticate actors at manufacture, shipment, repair and reuse. Flag missing transitions and implausible events for investigation." }, { title: "Expose permitted information", detail: "Give customers, regulators and service partners different views. Support corrections and recalls without rewriting historical accountability." }],
    controls: [{ risk: "False data becomes permanent", control: "Verify suppliers and sample physical evidence; preserve correction history." }, { risk: "Identifier copied onto counterfeit goods", control: "Evaluate tamper resistance, duplicate-scan detection and inspection procedures." }, { risk: "Commercial secrets exposed", control: "Separate public product facts from restricted supplier and composition data." }],
    notFit: "Do not start with a shared ledger if suppliers cannot supply consistent data. Identifier and ERP integration may deliver more immediate value.",
    measures: ["Supplier evidence completeness", "Time to trace a recalled batch", "Unresolved identifier and custody anomalies"],
    pilot: ["Choose one product family and a manageable supplier group.", "Agree on data fields, access rights and correction ownership.", "Test copied labels, expired certificates and a recall.", "Validate results against physical inventory and existing records."],
    questions: ["How does the identifier stay attached to the physical product?", "Who validates supplier claims?", "Which fields are public and which are commercially restricted?"],
    reference: { label: "European Commission: Ecodesign for Sustainable Products", href: "https://commission.europa.eu/energy-climate-change-environment/standards-tools-and-labels/products-labelling-rules-and-requirements/ecodesign-sustainable-products-regulation_en", note: "Background on the product-policy framework. Requirements and implementation timing depend on the product group; blockchain is not the default legal requirement." },
    faqs: [{ q: "Does a product passport require blockchain?", a: "No. Evaluate interoperable identifiers, reliable data and access controls first." }, { q: "Can provenance records stop counterfeiting?", a: "They can support detection, but copied labels and false source data require physical controls and investigation." }]
  },
  "real-estate-fund-administration": {
    title: "Tokenized real estate fund operations", group: "Financial services", audience: "Property fund managers, administrators and investor operations teams",
    answer: "Real estate fund tokenization usually represents an interest in a legal vehicle, not direct title to a building. The operating challenge is coordinating investor eligibility, subscriptions, ownership records and distributions while respecting the fund's transfer and redemption terms.",
    workflow: [{ title: "Structure the interest", detail: "Define the fund or SPV, investor rights and official register. Identify whether the token is authoritative or a representation reconciled to another record." }, { title: "Onboard investors", detail: "Review identity, entity documentation and eligibility before accepting subscriptions. Link wallets to approved holders without exposing their documents." }, { title: "Service ownership", detail: "Reconcile balances and capital activity. Apply permitted-transfer rules and document wallet recovery and investor status changes." }, { title: "Distribute and report", detail: "Use approved income calculations to issue statements and payments. Preserve tax, reporting and audit responsibilities with the relevant specialists." }],
    controls: [{ risk: "Token and legal register diverge", control: "Define authority and reconciliation procedures before issuance." }, { risk: "Liquidity implied but unavailable", control: "Disclose transfer limits and redemption conditions; do not equate tokens with a functioning secondary market." }, { risk: "Incorrect distributions", control: "Require administrator-approved calculations and traceable payment reconciliation." }],
    notFit: "If the project expects tokens to solve illiquid underlying assets or avoid securities obligations, stop and revisit the commercial and legal model.",
    measures: ["Subscription processing time", "Register reconciliation breaks", "Distribution accuracy and support requests"],
    pilot: ["Choose one vehicle with approved legal documentation.", "Map register authority, custody and administrator responsibilities.", "Test a restricted transfer, lost wallet and distribution correction.", "Reconcile a full reporting period before opening broader distribution."],
    questions: ["What legal interest does the token represent?", "Who maintains the official investor register?", "What liquidity is actually available, and under which restrictions?"],
    reference: { label: "FSB: Financial stability implications of tokenisation", href: "https://www.fsb.org/2024/10/the-financial-stability-implications-of-tokenisation/", note: "A risk framework for tokenized assets, including operational dependencies and liquidity mismatch. It does not validate a particular property product." },
    faqs: [{ q: "Does the token give direct property ownership?", a: "Only if the applicable legal structure establishes that right. Many models represent fund or SPV interests instead." }, { q: "Does tokenization guarantee liquidity?", a: "No. Buyers still need permitted counterparties, market demand and a viable transfer or redemption mechanism." }]
  },
  "stablecoin-payouts-remittances": {
    title: "Stablecoin payouts and treasury settlement", group: "Financial services", audience: "Fintechs, marketplaces and international treasury teams",
    answer: "Stablecoin payouts move value through a digital settlement asset between funding and recipient delivery. An onchain transfer can be fast while local currency delivery remains slow or unavailable. Evaluate the complete corridor, including conversion, screening, liquidity and reconciliation.",
    workflow: [{ title: "Fund the payout", detail: "Confirm funding currency, conversion spread, stablecoin and network. Establish who holds funds and who can approve treasury movements." }, { title: "Validate the recipient", detail: "Check recipient identity, wallet or bank details and applicable screening requirements. Prevent wrong-network and unsupported-address instructions." }, { title: "Move and deliver value", detail: "Submit an approved transfer, monitor confirmation and arrange the local offramp where needed. Distinguish chain confirmation from usable recipient funds." }, { title: "Reconcile exceptions", detail: "Link funding, conversion, network transaction and local payment to one payout identifier. Route rejects and returns to a named operations owner." }],
    controls: [{ risk: "Recipient cannot obtain local currency", control: "Validate corridor coverage, bank compatibility, liquidity and actual delivery times." }, { risk: "Stablecoin or network disruption", control: "Assess issuer, redemption, chain and concentration risks with treasury owners." }, { risk: "Irrecoverable payment error", control: "Validate network and address, use approval thresholds and document recovery limitations." }],
    notFit: "Do not introduce stablecoins when recipients cannot use them, the corridor has no dependable offramp, or end-to-end costs exceed existing rails.",
    measures: ["Funding-to-usable-funds delivery time", "Total cost including FX, conversion and delivery", "Failed payout and reconciliation rates"],
    pilot: ["Select one corridor and recipient cohort.", "Compare full costs and delivery times with the existing provider.", "Test a bank rejection, stale screening result and network outage.", "Scale only after treasury, compliance and recipient support accept the workflow."],
    questions: ["Which entity provides local delivery in each corridor?", "Does the quote include conversion, network and withdrawal charges?", "How are failed offramps resolved after the onchain leg completes?"],
    reference: { label: "Stripe Global Payouts", href: "https://stripe.com/payouts", note: "A provider example separating recipient scenarios and integration options. Coverage, eligibility and stablecoin availability must be confirmed directly for your business." },
    faqs: [{ q: "Are stablecoin payouts instant?", a: "Onchain confirmation and recipient access to local funds are different milestones. Measure the entire payout, not only the chain transaction." }, { q: "Are stablecoins always cheaper?", a: "No. Include FX, conversion, network fees, local delivery, liquidity and operational costs in the comparison." }]
  },
  "private-credit-servicing": {
    title: "Private credit servicing and distribution", group: "Financial services", audience: "Private credit managers, loan servicers and fund operations teams",
    answer: "Digital private-credit infrastructure connects investor interests to loan servicing, reporting and distributions. The token layer can improve access and record handling; it does not improve borrower creditworthiness or remove the need for underwriting, covenant monitoring and recovery procedures.",
    workflow: [{ title: "Define the exposure", detail: "Distinguish a loan claim from an interest in a credit fund. Define investor rights, servicing authority and the record that governs ownership." }, { title: "Collect servicing events", detail: "Ingest borrower repayments, interest calculations, covenant data and delinquencies. Authenticate updates and retain the underlying documents." }, { title: "Reconcile and distribute", detail: "Apply approved allocation rules and fees. Reconcile borrower cash, fund accounts and investor payments before updating dashboards." }, { title: "Handle distress", detail: "Route covenant breaches and defaults to authorized decision makers. Communicate valuations, recovery actions and changes in distributions." }],
    controls: [{ risk: "Stale or optimistic loan data", control: "Set reporting frequency, evidence standards and escalation for overdue servicing updates." }, { risk: "Wrong cash allocation", control: "Reconcile repayments and approved waterfall calculations before payment." }, { risk: "Liquidity mismatch", control: "Align redemption and transfer terms with the underlying credit assets and available liquidity." }],
    notFit: "Do not build a distribution token before the servicing model, borrower evidence and default process are credible. Better investor access is not better credit risk.",
    measures: ["Servicing-data freshness", "Cash reconciliation exceptions", "Time to notify investors of material events"],
    pilot: ["Choose one loan pool or credit vehicle.", "Map borrower data, fund accounting and investor ownership.", "Test delayed repayment, covenant breach and a default scenario.", "Reconcile an interest and distribution cycle with the existing servicer."],
    questions: ["Who verifies borrower and covenant data?", "Can the system model fees, waterfalls and recovery proceeds?", "How are defaults reflected in investor reporting and valuations?"],
    reference: { label: "FSB: Financial stability implications of tokenisation", href: "https://www.fsb.org/2024/10/the-financial-stability-implications-of-tokenisation/", note: "Useful for evaluating asset risk, third-party dependencies and liquidity assumptions in digital investment products." },
    faqs: [{ q: "Does tokenization reduce borrower default risk?", a: "No. Underwriting, collateral, covenants and servicing remain the drivers of credit risk." }, { q: "Which record should investors rely on?", a: "The legal documents should identify authoritative ownership and servicing records. Reconcile token balances and dashboards to those records." }]
  },
  "ai-document-intelligence": {
    title: "AI document intelligence for regulated finance", group: "Enterprise operations", audience: "Compliance, fund operations and enterprise AI teams",
    answer: "Document intelligence extracts and organizes information from financial documents for controlled review. Its strongest use is reducing repetitive handling while preserving source evidence and human accountability. A fluent summary is not proof that a clause, identity or eligibility decision is correct.",
    workflow: [{ title: "Ingest securely", detail: "Classify documents and access rights. Define retention, processing location and whether any supplier may use the content for model training." }, { title: "Extract with provenance", detail: "Return structured fields linked to source pages and spans. Track document version and distinguish absent information from an inferred value." }, { title: "Review uncertainty", detail: "Route low-confidence and consequential outputs to qualified reviewers. Evaluate field accuracy on representative documents, including poor scans and unusual clauses." }, { title: "Publish approved records", detail: "Write only approved data to downstream systems. Log corrections and model versions so errors can be traced and affected records reprocessed." }],
    controls: [{ risk: "Hallucinated or missed clauses", control: "Require source-linked outputs and task-specific evaluation; do not rely on fluent wording." }, { risk: "Confidential data leakage", control: "Assess subprocessors, tenancy, training use, encryption and deletion controls." }, { risk: "Automation exceeds authority", control: "Separate extraction from consequential decisions and assign human approval boundaries." }],
    notFit: "Avoid autonomous approval where accuracy has not been measured, source evidence is unavailable, or sensitive data cannot be processed within approved controls.",
    measures: ["Field-level precision and recall", "Reviewer correction rate", "Approved-document turnaround time"],
    pilot: ["Build a labeled sample covering actual document variability.", "Define critical fields, error severity and acceptance thresholds.", "Test prompt injection, bad scans, missing fields and contradictory versions.", "Compare reviewed outputs and total handling time with the manual baseline."],
    questions: ["Can every field be traced to the original source?", "What is accuracy on our documents, rather than a generic benchmark?", "Can we prevent training use and verify deletion?"],
    reference: { label: "NIST AI Risk Management Framework", href: "https://www.nist.gov/itl/ai-risk-management-framework", note: "A voluntary risk-management foundation for evaluation and governance. It is not a certification that a particular model is safe for financial decisions." },
    faqs: [{ q: "Can AI approve KYC or investment documents?", a: "Use document extraction as decision support. Define approval authority, validate performance and obtain the relevant compliance review before automating consequential decisions." }, { q: "What is the most important vendor test?", a: "A representative, labeled evaluation on your documents with source-linked outputs and a measurable reviewer correction rate." }]
  },
  "identity-kyc-onboarding": {
    title: "Reusable identity and investor onboarding", group: "Financial services", audience: "Compliance officers, onboarding leaders and investment platforms",
    answer: "Reusable identity can reduce repeated collection of verified attributes, but an earlier KYC check does not automatically satisfy a new institution's obligations. Each receiving organization must assess assurance, freshness, permissions and its own screening and eligibility requirements.",
    workflow: [{ title: "Verify the identity", detail: "Establish the evidence, assurance level and issuing provider. Record which attributes were verified and when." }, { title: "Share permitted attributes", detail: "Let the user authorize a narrowly scoped presentation. Avoid sharing complete documents when a smaller verified attribute is sufficient." }, { title: "Apply current checks", detail: "Refresh sanctions and risk screening as required and assess the product's investor eligibility. Link wallets only through an approved association process." }, { title: "Maintain status", detail: "Revoke compromised credentials, update expired evidence and preserve the receiving institution's audit and access rights." }],
    controls: [{ risk: "Stale screening reused", control: "Separate persistent identity attributes from time-sensitive sanctions and risk checks." }, { risk: "Reliance responsibilities unclear", control: "Document assurance, access to evidence and institution-specific acceptance with compliance owners." }, { risk: "Cross-platform identity correlation", control: "Minimize disclosed attributes and evaluate correlation and consent risks." }],
    notFit: "Do not promise one-time KYC for every product or jurisdiction. Reuse is unsuitable when the receiving institution cannot obtain required evidence or trust the assurance process.",
    measures: ["Onboarding completion time", "Repeat-document requests", "Expired evidence and screening exceptions"],
    pilot: ["Choose one verified attribute and two cooperating institutions.", "Agree on evidence access, assurance and refresh responsibilities.", "Test expired credentials, sanctions changes and compromised wallet association.", "Review the evidence pack with the receiving compliance team."],
    questions: ["Which checks must be refreshed at every onboarding?", "Can our institution access the underlying evidence when required?", "Who is responsible if the originating identity check was wrong?"],
    reference: { label: "FATF Guidance on Digital Identity", href: "https://www.fatf-gafi.org/content/dam/fatf/documents/recommendations/pdfs/Guidance-on-Digital-Identity.pdf", note: "Background on digital identity assurance and customer due diligence. Institution and jurisdiction-specific reliance rules still need assessment." },
    faqs: [{ q: "Does reusable identity mean permanent KYC approval?", a: "No. Identity attributes and current screening have different lifecycles, and each institution must assess its own obligations." }, { q: "Can a wallet address prove investor eligibility?", a: "Not alone. Associate it with an approved identity and current product-specific eligibility through a controlled process." }]
  },
  "tokenized-treasury-products": {
    title: "Tokenized treasury and money market products", group: "Financial services", audience: "Asset managers, institutional treasury teams and fund distributors",
    answer: "Tokenized treasury products offer a digital representation of rights defined by an investment product's legal structure. Evaluate the issuer, underlying assets, eligibility, custody and redemption mechanics. A token balance is not the same thing as a bank deposit or unrestricted cash.",
    workflow: [{ title: "Assess the product", detail: "Read the legal structure, fees, underlying exposure and redemption terms. Distinguish a fund interest from a direct security claim or issuer obligation." }, { title: "Subscribe through approved access", detail: "Complete entity onboarding and eligibility checks. Confirm settlement currency, minimums and who may hold or transfer the token." }, { title: "Service valuation and holdings", detail: "Reconcile token balances with authoritative records and approved NAV data. Identify who publishes valuation and how interest or distributions are handled." }, { title: "Redeem and receive funds", detail: "Track redemption submission, approval and payment separately. Network availability does not eliminate fund cutoffs, banking hours or liquidity constraints." }],
    controls: [{ risk: "Product treated as cash", control: "Assess legal rights and market, issuer, custody and redemption risks against treasury policy." }, { risk: "Stale valuation", control: "Disclose valuation source, publication schedule and stale-data handling." }, { risk: "Redemption expectations mismatch", control: "Test actual payment delivery and review gates, queues and counterparties." }],
    notFit: "A product is not suitable for cash needs requiring unconditional immediate liquidity if its redemption or eligibility terms cannot meet those needs.",
    measures: ["Subscription and redemption completion time", "Holdings-versus-register exceptions", "Net return after all product and transaction costs"],
    pilot: ["Compare legal rights and redemption terms across candidate products.", "Obtain treasury approval for issuer, custody and settlement exposure.", "Test subscription, restricted transfer and a stressed redemption scenario.", "Reconcile statements and actual fund delivery before increasing allocation."],
    questions: ["What exactly is our legal claim?", "Who can redeem, when, and into which currency?", "How do NAV, fees and distributions affect the token balance?"],
    reference: { label: "Ondo OUSG", href: "https://ondo.finance/ousg", note: "A product example for studying eligibility and redemption disclosures. This guide is not an endorsement; verify current terms and suitability directly." },
    faqs: [{ q: "Are tokenized treasuries equivalent to cash?", a: "No. Rights, liquidity and risks depend on the product structure, underlying assets and redemption process." }, { q: "Does 24/7 transfer mean 24/7 redemption?", a: "No. Transfer availability and the ability to receive redemption proceeds are distinct product features." }]
  },
  "tokenized-collateral-liquidity": {
    title: "Tokenized collateral and intraday liquidity", group: "Financial services", audience: "Banks, broker-dealers, custodians and collateral operations teams",
    answer: "Tokenized collateral coordinates eligible asset records with pledging, substitution and settlement. Its practical value is improved collateral mobility between accepted counterparties. Legal enforceability, custody and settlement design remain essential even when transfer instructions are programmable.",
    workflow: [{ title: "Establish eligibility", detail: "Identify the asset, legal owner and custodian. Approve haircuts, concentration limits and counterparties before making the record available." }, { title: "Pledge and lock", detail: "Check available collateral and record the encumbrance. Prevent conflicting pledges across the digital record and custody system." }, { title: "Settle or substitute", detail: "Coordinate asset and payment legs with defined finality. Re-evaluate eligibility and margin when prices or counterparties change." }, { title: "Release or unwind", detail: "Resolve repayment, release, failed settlement and default under the agreed legal and operational rules." }],
    controls: [{ risk: "Duplicate encumbrance", control: "Reconcile locks and pledges to custodian records and authorized collateral agreements." }, { risk: "Stale prices or haircuts", control: "Control valuation sources and define fallback eligibility limits." }, { risk: "Unclear settlement finality", control: "Document payment-asset risk, rollback limitations and legal finality for both legs." }],
    notFit: "Do not automate collateral movement when legal claims, custody locks or counterparty acceptance are unresolved. A faster message is not an enforceable pledge.",
    measures: ["Time to locate and mobilize eligible collateral", "Failed settlement and margin exceptions", "Custody-versus-pledge reconciliation breaks"],
    pilot: ["Select one collateral asset and controlled counterparty group.", "Map encumbrance, eligibility and legal-finality responsibilities.", "Test price shocks, substitutions, failed payment and default.", "Compare actual collateral availability and operations effort with the baseline."],
    questions: ["Can the same asset be pledged elsewhere?", "What establishes finality on each settlement leg?", "How are price-source failure and substitutions handled?"],
    reference: { label: "MAS Project Guardian", href: "https://www.mas.gov.sg/schemes-and-initiatives/project-guardian", note: "Institutional tokenization initiatives provide context for controlled experiments. Participation or pilot activity is not proof that any proposed collateral model is production-ready." },
    faqs: [{ q: "Does a collateral token establish an enforceable pledge?", a: "Not alone. The legal agreement, custody model and applicable law determine the rights and their enforcement." }, { q: "What should a pilot measure?", a: "Measure eligible collateral availability, settlement exceptions and reconciliation effort, rather than token transfer speed alone." }]
  },
  "digital-fund-administration-transfer-agent": {
    title: "Digital fund administration and investor records", group: "Financial services", audience: "Fund administrators, transfer agents and asset managers",
    answer: "Digital fund operations connect subscriptions, ownership, NAV, corporate actions and reporting. Token balances must align with the official holder record and fund accounting. A tokenization platform can coordinate these workflows but does not automatically assume regulated administrator or transfer-agent responsibilities.",
    workflow: [{ title: "Approve subscriptions", detail: "Connect reviewed documents, investor eligibility and settled subscriptions. Do not issue interests from an unconfirmed payment instruction." }, { title: "Maintain the register", detail: "Update official ownership and reconcile token balances. Define whether the chain or another system is authoritative and how corrections are approved." }, { title: "Process fund events", detail: "Use approved NAV, capital activity and distribution calculations. Connect transfers and redemptions to the investor record and fund ledger." }, { title: "Report and resolve", detail: "Deliver statements and relevant tax documents. Resolve lost access, deceased holders, failed payments and reporting corrections through approved procedures." }],
    controls: [{ risk: "Conflicting sources of truth", control: "Name the authoritative register and control reconciliation and correction rights." }, { risk: "Unapproved corporate action", control: "Separate calculation, approval and execution with traceable versioning." }, { risk: "Vendor role ambiguity", control: "Contractually assign administration, registry, custody and investor-support responsibilities." }],
    notFit: "Do not launch a token layer before official records, accounting integrations and exception ownership are defined. Fragmentation can increase rather than reduce operating risk.",
    measures: ["Subscription-to-register completion", "Daily record reconciliation breaks", "Statement and corporate-action correction rates"],
    pilot: ["Select a fund and define the authoritative register.", "Connect subscriptions, NAV and one distribution workflow.", "Test a lost wallet, restricted transfer and redemption correction.", "Run parallel records through a complete reporting cycle."],
    questions: ["Who legally maintains the holder register?", "Can we export all records and migrate providers?", "How are token corrections reflected in accounting and statements?"],
    reference: { label: "SEC transfer agents", href: "https://www.sec.gov/about/divisions-offices/division-trading-markets/transfer-agents", note: "Background on transfer-agent responsibilities in the US. Relevant registration and obligations depend on the structure and jurisdiction." },
    faqs: [{ q: "Can a smart contract replace a transfer agent?", a: "Technology can support recordkeeping, but legal responsibilities do not disappear. Determine who performs each required function." }, { q: "Which system should be authoritative?", a: "The legal and operating model must explicitly decide. Other records should reconcile to that source under controlled procedures." }]
  },
  "proof-of-reserve-tokenized-assets": {
    title: "Proof of reserve and asset verification", group: "Financial services", audience: "Issuers, custodians, risk teams and tokenized-asset platforms",
    answer: "Proof-of-reserve workflows publish evidence about specified backing assets and may trigger safeguards when thresholds are breached. They do not automatically establish liabilities, ownership, redemption rights or financial solvency. State exactly what is verified, by whom and at what time.",
    workflow: [{ title: "Define the scope", detail: "Specify assets, obligations and relevant accounts. Identify whether data is a point-in-time attestation, live feed or independently audited statement." }, { title: "Authenticate evidence", detail: "Connect authorized custody or accounting sources. Record methodology, timestamp and the party responsible for each assertion." }, { title: "Compare and act", detail: "Reconcile backing with token supply and defined liabilities. Set stale-data and shortfall thresholds, then test warnings or mint restrictions." }, { title: "Disclose limitations", detail: "Publish update frequency, exclusions and failure procedures. Preserve historical evidence and communicate disputed or unavailable readings." }],
    controls: [{ risk: "Assets mistaken for solvency", control: "Disclose liabilities, encumbrances and scope limitations separately." }, { risk: "Stale or manipulated feed", control: "Authenticate sources, monitor age and use independent checks or fallback procedures." }, { risk: "Safeguard harms users", control: "Review mint and redemption controls carefully; reserve changes should not trigger unexplained restrictions." }],
    notFit: "Do not advertise verified backing when authoritative data is inaccessible or the methodology excludes material obligations without clear disclosure.",
    measures: ["Evidence age and feed availability", "Unexplained supply-versus-backing differences", "Time to detect and escalate a reserve exception"],
    pilot: ["Define the claims the dashboard is allowed to make.", "Reconcile one authoritative asset source with token supply.", "Test missing feeds, a shortfall and disputed custody data.", "Have an independent reviewer assess both the evidence and limitations."],
    questions: ["Are liabilities and encumbrances included?", "Who controls the underlying source data?", "What happens when reserve evidence becomes stale?"],
    reference: { label: "Chainlink Proof of Reserve", href: "https://chain.link/proof-of-reserve", note: "A vendor example of reserve-data infrastructure. Evaluate the particular feed's source, methodology and controls rather than assuming every feed offers identical assurance." },
    faqs: [{ q: "Is proof of reserve a full audit?", a: "No. Scope, liabilities, legal ownership and financial condition need separate assessment; a reserve feed is one part of the evidence." }, { q: "Should a stale feed mean reserves are missing?", a: "No. Distinguish unavailable evidence from an actual shortfall, and define appropriate alerts and controls for each condition." }]
  }
};
